- hosts: all
  gather_facts: yes
  tasks:
    - debug:
        msg: "SSH user: {{ ansible_user }}"

- hosts: all
  gather_facts: yes
  roles:

- hosts: all
  gather_facts: yes
  become: true
  roles:
    - set_facts
    - certificates
    - nginx
